### PR TITLE
added library of test-points

### PR DESCRIPTION
**Pull request by jkriege2**
moved from https://github.com/KiCad/Connectors.pretty/pull/87

2017-09-17 10_06_11-3d viewer
2017-09-17 10_05_52-pcbnew d__kicad_kicad_review-project2_kicad_review-project2 kicad_pcb

see also (3D models):
- https://github.com/KiCad/kicad-library/pull/1626
- https://github.com/KiCad/packages3D/pull/133
- https://github.com/KiCad/packages3D-source/pull/55

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi @SchrodingersGat 

moved this here ... please note that the KLC-check-scripts don't run in this repo yet ... I fixed some of the KLC-issues seen in the old PR, but the ones for VIRTUAL components still remain, as the script's don't know VIRTUALs.

BTW: Having footprints without actual components as VIRTUAL is correct, right?

Best,
JAN

**Comment by SchrodingersGat** [comment]
I'll enable our friend Travis for this repo. For footprints that do not actually have a physical component loaded, virtual is correct. We need to add that to the rules!!

**Comment by SchrodingersGat** [comment]
Sorry, it needed the `travis.yml` file to run :)

**Comment by SchrodingersGat** [comment]
I'll add a note in my KLC updates regarding the `Virtual` component style.

**Comment by jkriege2** [comment]
OK!
JAN

**Comment by SchrodingersGat** [comment]
selection_007

**Comment by SchrodingersGat** [comment]
I'm happy with this PR, thanks for your fine work. I haven't had much time to check through PRs I have been focusing on the library reorganisation stuff. v5 might happen soon!

**Comment by jkriege2** [comment]
v5 would also mean we get the new library format?

**Comment by SchrodingersGat** [comment]
I think that's not until v6 :(

**Comment by jkriege2** [comment]
so what will change for us in v5? Lib-organization at least?

**Comment by SchrodingersGat** [comment]
Goals:

* Revamp KLC and put on website
* Proper information about libraries on website
* Merge all .pretty repos
* Reorganize symbol libs as per our other discussion
* Reorganize .pretty libs as per our other discussion
* kicad-library becomes legacy
* New repos are: kicad-symbols / kicad-footprints / kicad-packages3d / kicad-templates

**Comment by pointhi** [comment]
Please note https://github.com/KiCad/Measurement_Points.pretty also contains testpoints.

**Comment by jkriege2** [comment]
Oh ... I didn't see these ... we should merge the two Repos ... which should we choose as basis? I would propose the Connectors_TestPoints.pretty, as the term TestPoints seems to be commonly used by the manufacturers of such devices ... What do you think?

JAN

**Comment by jkriege2** [comment]
in Addition: using this Repo here has the advantage, that we don't have to move 3D models, when merging ;-)

I can do a PR, when we decide which repo to use ... I will then maybe also rename the MeaurementPoints into the TestPoint-nomenclature ... OK?

JAN

**Comment by pointhi** [comment]
I'm fine with moving the footprints into this repo

**Comment by jkriege2** [comment]
OK, PR is out there: https://github.com/KiCad/Connectors_TestPoints.pretty/pull/2

**Comment by poeschlr** [comment]
@SchrodingersGat 
Are the developers ok with merging footprint repos?
Is the github plugin finally be put to rest or is it going to be re written to allow for footprints in a single repo?

**Comment by SchrodingersGat** [comment]
@poeschlr 

> Are the developers ok with merging footprint repos?

I'm not sure either way. Independently, I think it's a good idea.

> Is the github plugin finally be put to rest or is it going to be re written to allow for footprints in a single repo?

Still working on this. The plan is to release /kicad-footprints/ for v5 and leave the .pretty repos intact. Then we can wean people off the plugin and convince the devs to drop it.

**Comment by poeschlr** [comment]
Maybe we can at least convince them to not have the github plugin as the default option. As long as it is the default most users will use it. (Nobody reads documentation. Heck most people don't even read everything we tell them on the forum. Today i had one special guy who only read the first sentence of a post i linked that was an answer to a different question but would have had important information for him later on. Resulted in him now using a connector symbol to represent an IC.)

**Comment by SchrodingersGat** [comment]
Agreed. We need to propose a logical way to incorporate libraries in the installer (but without bloating the size of the installer for people who already have libraries installed).

That would allow us to negate most problems, I think.

Do you have any knowledge about cross-platform packaging? Perhaps the solution would have to be bespoke for each OS? 

Or, we develop a cross-platform app (either separate to KiCad or integrated) for downloading libraries at install time...

**Comment by poeschlr** [comment]
I don't think footprints add much to the size. The size problem stems from the 3d models. So i assume you are talking about having a way to get all 3 types of libs.

I don't have any expirience with packagers. I anyway think the best option would be to have some sort of lib downloader within kicad. (One place for all 3 types of libs.) If it is outside kicad most people might miss that it is there. If it is only available during install time how could users update their lib later on. (They might not want to update kicad itself but only the lib. We could also decide to have more lib releases than there are kicad releases.)

I think the easiest way would be to have a tool similar to the footprint or 3d models downloader but for all 3 types of lib. Maybe it could also list releases? 
Opening kicad the first time would trigger a message that the libs still need to be downloaded. (If no libs are found.) We could also have a message pop up if the libs are quite old or if a new lib release exists. This way they do not need to be included in the kicad installer at all. (If packagers wish to have them included for their os they can do so. It would be their responsibility that it works correctly.)

**Comment by SchrodingersGat** [comment]
What you suggest is probably the best approach. But also a lot of work :) Once the KLC / website stuff is "done" I'll try to have a think about how it might all fit together.

**Comment by pointhi** [comment]
> I think the easiest way would be to have a tool similar to the footprint or 3d models downloader but for all 3 types of lib. Maybe it could also list releases?

I started with such a tool. Using libgit2 it's pretty easy to get full git integration. My problem was more with the gui, because using wx with python is not straight forward

**Pull request merged**
